on: [pull_request]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read


jobs:
  test-python:
    uses: NERC-CEH/dri-cicd/.github/workflows/test-python.yml@main
    with:
      optional_dependencies: "[lint,test,all]"